/* Amplify Params - DO NOT EDIT
	API_CENSUSEXPLORER_FAMILYDATATABLE_ARN
	API_CENSUSEXPLORER_FAMILYDATATABLE_NAME
	API_CENSUSEXPLORER_GRAPHQLAPIENDPOINTOUTPUT
	API_CENSUSEXPLORER_GRAPHQLAPIIDOUTPUT
	API_CENSUSEXPLORER_INCOMEDATATABLE_ARN
	API_CENSUSEXPLORER_INCOMEDATATABLE_NAME
	ENV
	REGION
Amplify Params - DO NOT EDIT */

exports.handler = async (event) => {
  let { FSAs } = event.arguments;
  console.log(FSAs);
  // TODO implement
  return FSAs;
};
